#cloud-config
package_update: true
package_upgrade: true

write_files:
  - path: /etc/ssh/sshd_config
    permissions: "0644"
    content: |
      # Cambio de puerto SSH a 2022
      Port 2022

runcmd:
  - systemctl restart sshd

final_message: "Configuración básica completada"