#cloud-config
package_update: true
package_upgrade: true

write_files:
  - path: /etc/ssh/sshd_config
    permissions: "0644"
    content: |
      PermitRootLogin yes
      PasswordAuthentication yes
      Port 2022


runcmd:
  - systemctl restart sshd

final_message: "Configuración básica completada"